# e) Considere que los siguientes patrones de entrada son aplicados a una capa de perceptrones lineales, con umbrales nulos para todos ellos, obteniendo las respectivas salidas. Obtener la matriz de pesos sinápticos W.

In [8]:
import torch

class SingleLayerNet(torch.nn.Module):
    def __init__(self, D_in, D_out):
        """
        In the constructor we instantiate one nn.Linear modules and assign them as
        member variables.
        """
        super(SingleLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, D_out, bias=True)

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        y_pred = self.linear1(x)
        return y_pred

# N is batch size; D_in is input dimension;
# D_out is output dimension.
N, D_in, D_out = 3, 4, 3

# Create Tensors to hold inputs and outputs
x = torch.tensor(
    [[1, 0, 0, 0], 
    [0, 1, 0, 0], 
    [0, 0, 1, 0]], dtype=torch.float32)
y = torch.tensor(
    [[5, 1, 0],
    [-2, 1, 6], 
    [-2, 4, 3]], dtype=torch.float32)

# Construct our model by instantiating the class defined above
model = SingleLayerNet(D_in, D_out)

# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters of the single
# nn.Linear module which is member of the model.
# criterion = torch.nn.BCEWithLogitsLoss(size_average=False)
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=3e-3)
for t in range(500):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

99 17.417551040649414
199 5.14152717590332
299 1.5423457622528076
399 0.4628644287586212
499 0.13890868425369263


In [5]:
x = torch.tensor(
    [[1, 0, 0, 0], 
    [0, 1, 0, 0], 
    [0, 0, 1, 0]], dtype=torch.float32)
model(x).sigmoid()

tensor([[0.9916, 0.7382, 0.5363],
        [0.1316, 0.7435, 0.9971],
        [0.1322, 0.9801, 0.9530]], grad_fn=<SigmoidBackward>)

In [6]:
model(x).softmax(dim=0)

tensor([[0.9974, 0.0512, 0.0031],
        [0.0013, 0.0526, 0.9417],
        [0.0013, 0.8962, 0.0552]], grad_fn=<SoftmaxBackward>)

In [35]:
import torch

class DoubleLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we instantiate one nn.Linear modules and assign them as
        member variables.
        """
        super(DoubleLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H, bias=True)
        self.linear2 = torch.nn.Linear(H, D_out, bias=True)

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        h_out = self.linear1(x).sigmoid()
        y_pred = self.linear2(h_out)
        return y_pred

# N is batch size; D_in is input dimension;
# D_out is output dimension.
N, D_in, H, D_out = 3, 4, 3, 3

# Create Tensors to hold inputs and outputs for 
x = torch.tensor(
    [[1, 0, 0, 0], 
    [0, 1, 0, 0], 
    [0, 0, 1, 0]], dtype=torch.float32)
y = torch.tensor(
    [[5, 1, 0],
    [-2, 1, 6], 
    [-2, 4, 3]], dtype=torch.float32)
    
    # Construct our model by instantiating the class defined above
model = DoubleLayerNet(D_in, H, D_out)

# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters of the double
# nn.Linear modules which is member of the model.
# criterion = torch.nn.BCEWithLogitsLoss(size_average=False)
criterion = torch.nn.MSELoss(reduction='sum')

optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
for t in range(5000):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

99 64.359130859375
199 56.658287048339844
299 54.929115295410156
399 53.14686584472656
499 50.48100280761719
599 46.58555603027344
699 41.48737716674805
799 35.655818939208984
899 29.738468170166016
999 24.29113006591797
1099 19.66340446472168
1199 15.982149124145508
1299 13.199359893798828
1399 11.169364929199219
1499 9.717305183410645
1599 8.681288719177246
1699 7.930127143859863
1799 7.3657355308532715
1899 6.918525695800781
1999 6.5408406257629395
2099 6.200893402099609
2199 5.877995014190674
2299 5.5591254234313965
2399 5.236680507659912
2499 4.907017707824707
2599 4.569570064544678
2699 4.226202487945557
2799 3.880587339401245
2899 3.5375216007232666
2999 3.2021634578704834
3099 2.879335880279541
3199 2.5730433464050293
3299 2.286233425140381
3399 2.0207738876342773
3499 1.7775743007659912
3599 1.5567700862884521
3699 1.3578885793685913
3799 1.1800340414047241
3899 1.0219975709915161
3999 0.8823839426040649
4099 0.7596942186355591
4199 0.6523909568786621
4299 0.5589549541473389
4

In [36]:
x = torch.tensor(
    [[1, 0, 0, 0], 
    [0, 1, 0, 0], 
    [0, 0, 1, 0]], dtype=torch.float32)
model(x).sigmoid()

tensor([[0.9923, 0.7506, 0.4733],
        [0.1144, 0.7455, 0.9969],
        [0.1346, 0.9796, 0.9616]], grad_fn=<SigmoidBackward>)

In [37]:
model(x).softmax(dim=0)

tensor([[9.9780e-01, 5.5703e-02, 2.5638e-03],
        [9.9688e-04, 5.4219e-02, 9.2594e-01],
        [1.2012e-03, 8.9008e-01, 7.1494e-02]], grad_fn=<SoftmaxBackward>)